-- =============================================================================
-- DGRAD CONTROLE — recette du flux direct Service d'assiette
-- =============================================================================
--
-- Le répertoire est volontairement vide au démarrage de la recette. Les
-- assujettis doivent être créés depuis l'interface du Service d'assiette afin
-- de vérifier que le NIF est produit automatiquement par PostgreSQL.
--
-- Les anciennes informations intermédiaires ne sont plus injectées ici.
